# -*- coding: utf-8 -*-
"""preprocess_movie_review.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18kKQg3oqu-qldSw1VsIz861BTx-ze9yn
"""

import pandas as pd
from konlpy.tag import Okt
import re

df = pd.read_csv('./crawling/reviews_2017_53_page.csv', index_col=0)   #0번 컬럼을 index로 써라
print(df.head())

okt = Okt()

#불용어 제거 
stopwords = pd.read_csv('./crawling/stopwords.csv', index_col=0)
#기존 불용어에 더해서 불용어로 할것들 추가
#불용어를 리스트로 바꾸기
movie_stopwords = ['영화', '배우', '감독']  #영화리뷰에서 필요없는 단어. 
stopwords_list = list(stopwords.stopword) + movie_stopwords  #list(stopwords.stopword)는 stopwords라는 df의 stopword column을 리스트로 바꾼다.

#불용어, 1글자 지우는
# words = []
# for word in df_cleaned_token['word']:
#   if len(word) > 1:    #한글자 빼고
#     if word not in stopwords_list:    #불용어 빼고
#       words.append(word)
# print(words)
#
# #하나의 문장으로 만들기
# cleaned_sentence = ' '.join(words)
# print(cleaned_sentence)

#전체 preprocess
#리뷰 모든 문장에 적용
count = 0
cleaned_sentences = []
for sentence in df.reviews:
  count += 1
  if count % 10 == 0:  #10개마다 진행상황 확인
    print('.', end='')
  if count % 100 == 0:
    print('')   #100개마다 줄바꿈하기
  sentence = re.sub('[^가-힣 | ' ']', '', sentence)   #한글, 띄어쓰기만 남기기
  token = okt.pos(sentence, stem=True)   #형용사, 동사는 원형으로
  df_token = pd.DataFrame(token, columns=['word', 'class'])
  df_cleaned_token = df_token[(df_token['class'] == 'Noun')|
                            (df_token['class'] == 'Verb')|
                            (df_token['class'] == 'Adjective')]  
  words = []
  for word in df_cleaned_token['word']:
    if len(word) > 1:    #한글자 빼고
      if word not in stopwords_list:    #불용어 빼고
        words.append(word)
  cleaned_sentence = ' '.join(words)   #하나의 문자로 이어붙이고
  cleaned_sentences.append(cleaned_sentence)
df['cleaned_sentences'] = cleaned_sentences
print(df.head())

print(df.info())

df = df[['titles', 'cleaned_sentences']]
print(df.info())
df.to_csv('./crawling/cleaned_review_2017.csv')

"""# 강사님 코드 
https://colab.research.google.com/drive/1Zmn9vhf2Vhi3zeA5Nhn1CjB5Maa2nfBC?usp=sharing

"""